### ISSUE TITLE
bug: update the way to get latest release

### ISSUE THREAD

**Issue by Seasawher** [oliver-butterley/lean-update#26]
In this workflow, it downloads v4.9.1 as the latest release. 

see https://github.com/lean-ja/lean-by-example/actions/runs/9883761323/job/27299040801#step:3:1

but actually v4.10.0-rc2 is the latest.
This is a bug of the way to get latest release. 

important note: this issue make the workflow fail

**Comment by oliver-butterley** [comment]
This behaviour is because `gh release list --repo leanprover/lean4` believes that v4.9.1 is the latest release:

![image](https://github.com/oliver-butterley/lean-update/assets/51876429/396ca7b1-0817-4a8e-8fcb-fde59d0918e5)

In sense it is correct! As far as I can see, this is the first time in the release history of Lean 4 that the current strategy of lean-update fails. Not clear the best strategy to extract the wanted release from [gh releases list](https://cli.github.com/manual/gh_release_list).

**Comment by Seasawher** [comment]
If v4.9.2 or newer version come, I will think this issue seriously. I don't came up with any easy way to fix this.
