### ISSUE TITLE
Exception calling ".ctor" with "1" argument(s):

### ISSUE THREAD

**Issue by Seasawher** [oliver-butterley/lean-update#37]
```
Run /home/runner/work/_actions/oliver-butterley/lean-update/v1-alpha/scripts/getLatest.ps1
ForEach-Object: /home/runner/work/_actions/oliver-butterley/lean-update/v1-alpha/scripts/getLatest.ps1:10
Line |
  10 |  … $versions | ForEach-Object { [System.Management.Automation.SemanticVe …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling ".ctor" with "1" argument(s): "The input string '' was
     | not in a correct format."
Error: Process completed with exit code 1.
```
see: https://github.com/Seasawher/mathlib4-tactics/actions/runs/11176249532/job/31069206463

**Comment by oliver-butterley** [comment]
There was a release marked as `revert_lake_changes`. Did this cause the error because the semver sorting wasn't sufficiently robust for such? Was this a problem with the [command](https://github.com/oliver-butterley/lean-update/blob/de5132eeb8aa8505956bbd3dcd512de5d32eb571/scripts/getLatest.ps1#L7) ` ForEach-Object { $_ -replace '^v' }`?

![image](https://github.com/user-attachments/assets/6d572543-4a53-4258-9fba-30ae0c601506)

**Comment by Seasawher** [comment]
@oliver-butterley Thank you!!
